# 2D Lists

We have seen a list can hold many items:

```
my_list = ['cheddar', 'spam', 'parrot']
ints = [2, 67, 5, 3, 9, -2]
```

We have so far avoided mixing types, though Python doesn't mind:

`stuff = [42, 'good-bye', 3.14159]`

What if a list contained more lists? Let's look at a simple case of a list
contianing two lists. We can delcare it immediately:

In [0]:
a = [[1, 2], [3, 4]]
print(a)

[[1, 2], [3, 4]]

OK, now let's look inside. Recall the notation for accessing a list element
by index, using the list identifier with index: `list[index]`

The 'outside' list is `a`. The first 'inside' list is at index `0`, so it
is `a[0]`. The second 'inside' list is at index `1` and so it is `a[1]`.

Let's check:

In [0]:
print('the list: ', a)
print('the first list: ', a[0])
print('the second list: ', a[1])

So how do we get the number `1`, which is the first element of the first list?

We simply go down one more level. The element we want is at index `0` of the list `a[0]`, so it is `a[0][0]`!

In [0]:
print(a[0][0])    # first list, first element
print(a[0][1])    # first list, second element
print(a[1][0])    # second list, first element
print(a[1][1])    # second list, second element

It's sometimes easier to think of lists within lists as a table, hence the name 2D List, like this:

```
a = [[1, 2],
     [3, 4]]
```

Here, the first list inside `a` is the first 'row', and the second list is the second 'row'. There are also 'columns', which are the elements in each row that are in the same position 'vertically'.

<table>
    <tr>
        <td></td> <td>col 0</td> <td>col 1</td>
    </tr>
    <tr>
        <td>row 0</td> <td>1</td> <td>2</td>
    </tr>
    <tr>
        <td>row 1</td> <td>3</td> <td>4</td>
    </tr>
</table>

Then for an expression such as `a[i][j]`, the first index represents the row number, and the second index represents the column number. So `a[3][5]` is the element at row index 3 (4th row) and column index 5 (6th column). Remember in Python index counting starts at `0`.

## Printing

Row by row:

In [0]:
for row in a:
    print(row)

[1, 2]
[3, 4]

Row by row without brackets:

In [0]:
for row in a:
    for item in row:
        print(item, end=' ')
    print()

1 2
3 4

Each element on its own line:

In [0]:
for row in a:
    for item in row:
        print(item)

1
2
3
4

Same as above, but by index:

In [0]:
for r in range(len(a)):       # Of course, you could use i and j, or row and col
    for c in range(len(a[r])):
        print(a[r][c])

1
2
3
4

Exercise for you: 

Row by row, without brackets, by index, e.g.

```
1 2
3 4
```

In [0]:
# your code here
a = [[1, 2],
     [3, 4]]

for i in range(len(a)):
    for j in range(len(a[i])):
        print(a[i][j], end=' ')
    print()

1 2
3 4

## Changing Values

While printing without the index is nice, if we want to change values, we need the index.

We do it like a regular list:

In [0]:
a = [[1, 2], [3, 4]]
print(a)

# change one value
a[0][0] = -9
print(a)

# change an entire row
a[1] = [5, -6]
print(a)

# change all values: change sign
for r in range(len(a)):
    for c in range(len(a[r])):
        a[r][c] *= -1
print(a)

# Exercise for you:
# reassign all values to to 0 and print to test
print()
for row in range(len(a)):
    for col in range(len(a[row])):
        a[row][col] = 0
print(a)

[[1, 2], [3, 4]]
[[-9, 2], [3, 4]]
[[-9, 2], [5, -6]]
[[9, -2], [-5, 6]]

[[0, 0], [0, 0]]

## More Fun

Of course, we need not confine ourselves to such dimensions.

Conventionally, we refer to the dimensions of a rectangular list as `m x n`, where `m` denotes rows and `n` denotes columns. For now, we won't worry too much about non-rectangular lists.

In [0]:
# 3x3 (3 rows, 3 cols)
b = [[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]]

# 2x4 (2 rows, 4 cols)
c = [[2,4,6,8],
     [3,6,9,12]]

# arbitrary length rows (non-rectangular)
d = [[-1, 0],
     [3,4,5,6,7,8],
     [9],
     []]

# not just int
s = [['do', 'not', 'forget'],
     ['about', 'strings', '!']]

# 3x3x3 cube!
t = [[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
     [[10, 11, 12], [13, 14, 15], [16, 17, 18]],
     [[19, 20, 21], [22, 23, 24], [25, 26, 27]]]

# Exercises

1. Print an `m x n` list nicely with commas between elements on the same row (but no trailing comma or space), e.g. the list `[[2, 4, 5], [3, 42, 1], [-5, 7, 0]]` would print as:

```
2, 4, 5
3, 42, 1
-5, 7, 0
```

In [0]:
# 1.
a = [[2, 4, 5], [3, 42, 1], [-5, 7, 0]]
for row in a:
    for col in row:
        print('{}'.format(col), end = ', ')
    print()

2, 4, 5,
3, 42, 1,
-5, 7, 0,

2. Write a function that finds the sum of all elements in a numeric 2D list, e.g. the sum of the elements in the list `[[235, 756], [13, 68]]` is `1072`.

In [0]:
# 2.
a = [[235, 756], [13, 68]]

sum = 0
for i in a:
    for j in i:
        sum += j
print(sum)

1072

3. Write a function that finds the sum of a single column of a `m x n` list. The parameters should be a list and the column number (index), e.g. the sum of column 1 in the list `[[2, -4, 9], [-6, 7, -2]]` is `-4 + 7 = 3`.

In [0]:
# 3.
a = [[2, -4, 9], 
     [-6, 7, -2]]

def sum(list, i):
    sum = 0
    for row in list:
        sum += row[i]
    print(sum)

sum(a, 1)

3

4. Write a function that prints the contents of a 2D list with labels indicating the row and column location of each item, e.g. the list `[['a', 'b'], ['c', 'd']]` should produce:

```
row 0, col 0: a
row 0, col 1: b
row 1, col 0: c
row 1, col 1: d
```

In [0]:
# 4. 

a = [['a', 'b'], ['c', 'd']]

def display(list):
    for i in range(len(list)):
        for j in range(len(list[i])):
            print('row {}, col {}: {}'.format(i, j, a[i][j]))

display(a)

row 0, col 0: a
row 0, col 1: b
row 1, col 0: c
row 1, col 1: d

5. Create an empty list. Ask the user for the required dimensions of an `m x n` numeric list. Then fill the list from the user (`int` for simplicity). It should ask for the dimensions, then return the list. Make sure the input prompt is labelled with the row and column, e.g. `enter data for row 2 col 3: `. At the end, print the 2D list. Can make this a function.

In [0]:
# 5. 

def get_list():
    list = []
    m = int(input('m: '))
    n = int(input('n: '))
    for i in range(m):
        row = []
        for j in range(n):
            row.insert(j, input('row {} col {}: '.format(i, j)))
        list.insert(i, row)
    return list

a = get_list()
print(a)

m: 5
n: 2
row 0 col 0: a
row 0 col 1: b
row 1 col 0: c
row 1 col 1: d
row 2 col 0: e
row 2 col 1: f
row 3 col 0: 2
row 3 col 1: g
row 4 col 0: h
row 4 col 1: True
[['a', 'b'], ['c', 'd'], ['e', 'f'], ['2', 'g'], ['h', 'True']]

6. Transpose a square 2D list; that is, for a 2D list of dimensions `m x m`, the values will be flipped across its diagonal, e.g.

```
for
A = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]

the transpose would be:
T = [[1, 4, 7],
     [2, 5, 8],
     [3, 6, 9]]
```

Can make this a function with the list as parameter; note: no need to return the list.

In [0]:
# 6.
import copy 
a = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
    
b = copy.deepcopy(a)
for i in range(len(a)):
    for j in range(len(a[i])):
        b[i][j] = a[j][i]
print(b)

[[1, 4, 7], [2, 5, 8], [3, 6, 9]]